(() => {
  const API = "/api/v1";
  const QUEUE_API = "/api/v1/playback-queue";
  const QUEUE_KEY = "daksh-queue-v7";
  const CACHE_NAME = "device-audio-v1";
  const esc = v => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  async function api(path, options = {}) { const res = await fetch(path.startsWith("/api/") ? path : API + path, {credentials:"include",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}); const text=await res.text(); let data={}; try{data=text?JSON.parse(text):{};}catch{} if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`); return data; }
  let state={items:[],current_index:-1,mode:"manual"};
  function persist(){try{localStorage.setItem(QUEUE_KEY,JSON.stringify(state));}catch{}}
  async function sync(){const d=await api(QUEUE_API);state={items:Array.isArray(d.items)?d.items:[],current_index:Number.isInteger(d.current_index)?d.current_index:-1,mode:d.mode||"manual"};persist();return state;}
  async function replace(items,current=0,mode="manual"){const clean=(items||[]).filter(x=>x&&(x.id!=null||x.track_id!=null));const d=await api(QUEUE_API,{method:"POST",body:JSON.stringify({mode:"replace",items:clean,current_index:clean.length?current:-1,playback_mode:mode})});state={items:Array.isArray(d.items)?d.items:clean,current_index:Number.isInteger(d.current_index)?d.current_index:(clean.length?current:-1),mode:d.mode||mode};persist();return state;}
  async function append(items){const clean=(items||[]).filter(x=>x&&(x.id!=null||x.track_id!=null));if(!clean.length)return state;const d=await api(QUEUE_API,{method:"POST",body:JSON.stringify({mode:"append",items:clean})});state={items:d.items||state.items,current_index:Number.isInteger(d.current_index)?d.current_index:state.current_index,mode:d.mode||state.mode};persist();return state;}
  async function clear(){const d=await api(QUEUE_API,{method:"DELETE"});state={items:d.items||[],current_index:Number.isInteger(d.current_index)?d.current_index:-1,mode:d.mode||"manual"};persist();return state;}
  async function setCurrent(index){const d=await api(`${QUEUE_API}/current`,{method:"POST",body:JSON.stringify({index})});state={items:d.items||state.items,current_index:Number.isInteger(d.current_index)?d.current_index:index,mode:d.mode||state.mode};persist();return state.items[state.current_index]||null;}
  async function remove(index){const d=await api(`${QUEUE_API}/${encodeURIComponent(index)}`,{method:"DELETE"});state={items:d.items||[],current_index:d.current_index??-1,mode:d.mode||state.mode};persist();return state;}
  async function reorder(from,to){const d=await api(`${QUEUE_API}/reorder`,{method:"POST",body:JSON.stringify({from,to})});state={items:d.items||[],current_index:d.current_index??-1,mode:d.mode||state.mode};persist();return state;}
  async function deviceCached(id){if(!("caches"in window)||id==null)return false;try{const c=await caches.open(CACHE_NAME);return!!await c.match(`${location.origin}${API}/playback/${encodeURIComponent(id)}`);}catch{return false;}}
  async function cacheFlags(items){return Promise.all(items.map(async t=>({...t,device_cached:await deviceCached(t.track_id??t.id)})));}
  async function playIndex(index){if(index<0||index>=state.items.length)return null;const track=await setCurrent(index);if(!track)return null;window.__dakshNowPlayingTrack=track;window.__dakshNowPlayingQueueIndex=index;if(window.__dakshQueuePlayTrack){await window.__dakshQueuePlayTrack(track,state.items,state.mode);}else{const audio=document.getElementById("audio");if(audio){audio.src=`${API}/playback/${encodeURIComponent(track.id??track.track_id)}`;await audio.play().catch(()=>{});}}return track;}
  async function playCurrent(){if(!state.items.length)return null;let index=state.current_index;if(!Number.isInteger(index)||index<0||index>=state.items.length)index=0;return playIndex(index);}
  async function next(){if(state.current_index+1<state.items.length)return playIndex(state.current_index+1);return null;}
  async function previous(){if(state.current_index>0)return playIndex(state.current_index-1);return null;}
  function sourceLabel(){return state.mode==="album"?"Album":state.mode==="playlist"?"Playlist":state.mode==="search"?"Search":"Queue";}
  async function renderOverlay(){let overlay=document.getElementById("dakshQueueOverlay");if(!overlay){overlay=document.createElement("div");overlay.id="dakshQueueOverlay";overlay.innerHTML=`<div class="dq-head"><div><b>Queue</b><small id="dqSource"></small></div><button id="dqClose">MENU</button></div><div id="dqBody"></div><div class="dq-foot"><button id="dqClear">Clear</button></div>`;document.getElementById("screen")?.appendChild(overlay);overlay.querySelector("#dqClose").onclick=()=>overlay.remove();overlay.querySelector("#dqClear").onclick=async()=>{if(confirm("Clear the queue?")){await clear();await renderOverlay();}};}const body=overlay.querySelector("#dqBody"),items=await cacheFlags(state.items);overlay.querySelector("#dqSource").textContent=state.items.length?` · ${sourceLabel()}`:"";body.innerHTML=items.length?items.map((t,i)=>`<div class="dq-row ${i===state.current_index?"cur":""} ${t.device_cached?"device-ready":""}" data-i="${i}"><div class="dq-main"><span class="dq-pos">${i+1}</span><div class="dq-text"><b>${esc(t.title||"Untitled")}</b><small>${esc(t.artist||"")}${t.album?` · ${esc(t.album)}`:""}</small><div class="dq-badges">${t.server_available?`<span class="dq-badge server">SERVER</span>`:""}${t.device_cached?`<span class="dq-badge device">ON DEVICE</span>`:""}</div></div></div><span class="dq-state">${t.device_cached?"Ready offline":""}</span></div>`).join(""):"<div class=\"dq-empty\">Queue is empty</div>";body.querySelectorAll(".dq-row").forEach(row=>row.onclick=()=>playIndex(Number(row.dataset.i)));}
  async function openQueue(){const overlay=document.getElementById("dakshQueueOverlay");if(overlay)overlay.remove();try{await sync();await renderOverlay();}catch(e){const screen=document.getElementById("screen");if(screen){const error=document.createElement("div");error.id="dakshQueueOverlay";error.className="dq-error";error.textContent=`Queue unavailable: ${e.message}`;screen.appendChild(error);}}}
  async function syncCurrentFromTrack(track){const id=track?.id??track?.track_id;if(id==null)return;const idx=state.items.findIndex(x=>String(x.id??x.track_id)===String(id));if(idx>=0&&idx!==state.current_index)await setCurrent(idx);}
  window.__dakshQueue={sync,replace,append,clear,remove,reorder,setCurrent,playIndex,playCurrent,next,previous,get state(){return state;},deviceCached};
  window.__dakshOpenQueue=openQueue;window.__dakshSetQueue=replace;window.__dakshQueueSyncCurrent=syncCurrentFromTrack;window.__dakshQueuePlay=playIndex;
  document.getElementById("audio")?.addEventListener("ended",()=>next());
  const style=document.createElement("style");style.textContent=`#dakshQueueOverlay{position:absolute;inset:22px 0 0;background:linear-gradient(180deg,var(--screen-top),var(--screen-bg));z-index:30;color:var(--screen-ink);display:flex;flex-direction:column}.dq-head{display:flex;align-items:center;justify-content:space-between;padding:7px 9px;border-bottom:1px solid rgba(0,0,0,.12);font-size:11px}.dq-head small{font-size:8px;color:var(--screen-sub);margin-left:4px}.dq-head button,.dq-foot button{border:0;background:transparent;color:var(--screen-sub);font-size:9px;font-weight:700}#dqBody{overflow:auto;min-height:0;flex:1}.dq-row{display:flex;align-items:center;justify-content:space-between;gap:5px;padding:6px 8px;border-bottom:1px solid rgba(0,0,0,.06);cursor:pointer}.dq-row.cur{background:linear-gradient(180deg,var(--sel-a),var(--sel-b));color:#fff}.dq-row.device-ready{box-shadow:inset 3px 0 0 #3f9e4d}.dq-main{display:flex;gap:6px;min-width:0}.dq-pos{width:14px;flex:none;text-align:right;font-size:8px;color:var(--screen-sub)}.dq-row.cur .dq-pos,.dq-row.cur small,.dq-row.cur .dq-state{color:#dbe6f5}.dq-text{min-width:0}.dq-text b,.dq-text small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dq-text b{font-size:9.5px}.dq-text small{font-size:8px;color:var(--screen-sub)}.dq-badges{display:flex;gap:3px;margin-top:2px}.dq-badge{display:inline-block;padding:1px 3px;border-radius:3px;font-size:6.5px;font-weight:800;letter-spacing:.04em}.dq-badge.device{background:#dcefdc;color:#286c31}.dq-badge.server{background:#dbe7f6;color:#2f5f97}.dq-row.cur .dq-badge.device{background:#c8e8cc;color:#205b28}.dq-row.cur .dq-badge.server{background:#c6d8ef;color:#234c79}.dq-state{font-size:7px;color:#3f7d47;flex:none}.dq-empty,.dq-error{padding:30px;text-align:center;font-size:10px;color:var(--screen-sub)}.dq-error{position:absolute;inset:22px 0 0;background:var(--screen-bg);z-index:30}.dq-foot{margin-top:auto;padding:5px 9px;border-top:1px solid rgba(0,0,0,.08);text-align:right}`;document.head.appendChild(style);
})();
