import worker from "./worker.js";
import { handleQueue, handleQueueCurrent, handleQueueReorder } from "./queue.js";
import { handleAcquisitionRoute } from "./acquisition_route.js";
import { populateTopCache } from "./top_cache.js";
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json",...extra}});
function cookie(req){return(req.headers.get("Cookie")||"").match(/(?:^|;\s*)music_session=([^;]+)/)?.[1]||null;}
async function sha256(text){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function requireAuth(env,req){const token=cookie(req);if(!token||!env.DB)return false;const row=await env.DB.prepare(`SELECT id_hash FROM sessions WHERE id_hash=? AND expires_at>?`).bind(await sha256(token),Math.floor(Date.now()/1000)).first();return!!row;}
async function verifyPassword(env,password){if(!env.PASSWORD_HASH||!env.PASSWORD_SALT)throw new Error("Authentication is not configured");let normalized=String(env.PASSWORD_SALT).replaceAll("-","+").replaceAll("_","/");normalized+="=".repeat((4-(normalized.length%4))%4);const binary=atob(normalized);const raw=Uint8Array.from(binary,c=>c.charCodeAt(0));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:raw,iterations:100000,hash:"SHA-256"},key,256);const actual=btoa(String.fromCharCode(...new Uint8Array(bits))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");return actual===String(env.PASSWORD_HASH);}
async function clearAllData(env,req){if(!(await requireAuth(env,req)))return json({error:"Authentication required"},401);let body;try{body=await req.json();}catch{return json({error:"Invalid JSON body"},400);}const password=String(body?.password||"");if(!password)return json({error:"Password is required"},400);try{if(!(await verifyPassword(env,password)))return json({error:"Invalid password"},401);let deletedObjects=0,cursor;do{const page=await env.AUDIO_BUCKET.list(cursor?{cursor}:{limit:1000});const objects=page.objects||[];if(objects.length){await env.AUDIO_BUCKET.delete(objects.map(o=>o.key));deletedObjects+=objects.length;}cursor=page.truncated?page.cursor:undefined;}while(cursor);await env.DB.batch(["album_cache","playlist_entries","general_cache","top_played_cache","download_jobs","album_sessions","albums","tracks","sessions"].map(table=>env.DB.prepare(`DELETE FROM ${table}`)));return json({ok:true,r2_objects_deleted:deletedObjects,tracks_deleted:true,playlist_deleted:true,cache_deleted:true,sessions_deleted:true});}catch(e){console.error("CLEAR ALL DATA ERROR:",e?.stack||e);return json({error:String(e?.message||e)},500);}}
async function listAcquisitions(env,req){if(!(await requireAuth(env,req)))return json({error:"Authentication required"},401);const url=new URL(req.url),limit=Math.min(200,Math.max(1,Number(url.searchParams.get("limit")||100))),status=url.searchParams.get("status");const sql=status?`SELECT j.id AS job_id,j.track_id,j.kind,j.status,j.provider,j.drive_file_id,j.format,j.mime_type,j.error,j.created_at,j.updated_at,t.title,t.artist,t.album,t.artwork_url,t.duration_ms,t.source,t.source_url FROM download_jobs j LEFT JOIN tracks t ON t.id=j.track_id WHERE j.status=? ORDER BY datetime(j.updated_at) DESC,datetime(j.created_at) DESC LIMIT ?`:`SELECT j.id AS job_id,j.track_id,j.kind,j.status,j.provider,j.drive_file_id,j.format,j.mime_type,j.error,j.created_at,j.updated_at,t.title,t.artist,t.album,t.artwork_url,t.duration_ms,t.source,t.source_url FROM download_jobs j LEFT JOIN tracks t ON t.id=j.track_id ORDER BY datetime(j.updated_at) DESC,datetime(j.created_at) DESC LIMIT ?`;const result=status?await env.DB.prepare(sql).bind(status,limit).all():await env.DB.prepare(sql).bind(limit).all();return json({items:result.results||[],limit});}
async function acquisitionSummary(env,req){if(!(await requireAuth(env,req)))return json({error:"Authentication required"},401);const result=await env.DB.prepare(`SELECT status,COUNT(*) AS count FROM download_jobs GROUP BY status`).all(),counts={};for(const row of result.results||[])counts[row.status]=Number(row.count||0);return json({counts,active:(counts.queued||0)+(counts.dispatched||0)+(counts.running||0)});}
async function uploadAudioCallback(env,req,jobId){const supplied=req.headers.get("X-Callback-Secret")||"",expected=String(env.CALLBACK_SECRET||"");if(!expected||supplied.length!==expected.length)return json({error:"Unauthorized"},401);let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=supplied.charCodeAt(i)^expected.charCodeAt(i);if(mismatch!==0)return json({error:"Unauthorized"},401);const job=await env.DB.prepare(`SELECT * FROM download_jobs WHERE id=?`).bind(jobId).first();if(!job)return json({error:"Job not found"},404);const url=new URL(req.url),provider=url.searchParams.get("provider")||null,format=url.searchParams.get("format")||"flac",contentType=req.headers.get("content-type")||(format==="mp3"?"audio/mpeg":"audio/flac"),storageKey=`tracks/${job.track_id}.${format}`;await env.AUDIO_BUCKET.put(storageKey,req.body,{httpMetadata:{contentType}});await env.DB.prepare(`UPDATE download_jobs SET status='complete',provider=?,drive_file_id=?,format=?,mime_type=?,error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(provider,storageKey,format,contentType,jobId).run();if(job.kind==="general"){await env.DB.prepare(`INSERT OR REPLACE INTO general_cache(track_id,drive_file_id,last_accessed_at) VALUES(?,?,CURRENT_TIMESTAMP)`).bind(job.track_id,storageKey).run();const limit=Math.max(1,Number(env.GENERAL_CACHE_LIMIT||30));await env.DB.prepare(`DELETE FROM general_cache WHERE track_id NOT IN (SELECT track_id FROM general_cache ORDER BY datetime(last_accessed_at) DESC LIMIT ${limit})`).run();}await env.DB.prepare(`UPDATE top_played_cache SET storage_key=?,updated_at=CURRENT_TIMESTAMP WHERE track_id=?`).bind(storageKey,job.track_id).run();return json({ok:true,storage_key:storageKey});}
function withPlayerDetails(response){return response;}
export default {async fetch(req,env,ctx){const url=new URL(req.url),path=url.pathname;if(path==="/api/v1/cache/top/populate"&&req.method==="POST")return populateTopCache(env,req);if(path==="/api/v1/admin/clear-all"&&req.method==="POST")return clearAllData(env,req);if(/^\/api\/v1\/tracks\/\d+\/acquire$/.test(path)){const response=await handleAcquisitionRoute(req,env);if(response)return response;}const audioUploadMatch=path.match(/^\/api\/v1\/jobs\/([^/]+)\/audio$/);if(audioUploadMatch&&(req.method==="PUT"||req.method==="POST"))return uploadAudioCallback(env,req,audioUploadMatch[1]);if(path==="/api/v1/queue/current"||path==="/api/v1/playback-queue/current"){const response=await handleQueueCurrent(req,env);if(response)return response;}if(path==="/api/v1/queue/reorder"||path==="/api/v1/playback-queue/reorder"){const response=await handleQueueReorder(req,env);if(response)return response;}if(path==="/api/v1/queue"||path==="/api/v1/playback-queue"||/^\/api\/v1\/(?:queue|playback-queue)\/\d+$/.test(path)){const response=await handleQueue(req,env);if(response)return response;}if((path==="/api/v1/acquisitions"||path==="/api/v1/jobs")&&req.method==="GET")return listAcquisitions(env,req);if(path==="/api/v1/acquisitions/summary"&&req.method==="GET")return acquisitionSummary(env,req);return worker.fetch(req,env,ctx);},};