import { backfillMissingMetadata } from "./metadata_backfill.js";

const json = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8" } });
function cookie(req) { return (req.headers.get("Cookie") || "").match(/(?:^|;\s*)music_session=([^;]+)/)?.[1] || null; }
async function auth(env, req) { const token=cookie(req);if(!token)return false;const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));const hash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("");const row=await env.DB.prepare(`SELECT id_hash FROM sessions WHERE id_hash=? AND expires_at>?`).bind(hash,Math.floor(Date.now()/1000)).first();return !!row; }
const slug=s=>String(s||"unknown").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase()||"unknown";
const naturalKey=(x,i)=>x.source_id?`apple-${slug(x.source_id)}`:`apple-${slug(x.title)}-${slug(x.artist)}-${slug(x.album)}-${Number(x.duration_ms)||0}-${i}`;
function isTopCacheRow(item){const value=item?.["100 Cache"]??item?.["100_Cache"]??item?.["100 cache"]??item?.["100Cache"]??item?.cache;return ["Y","YES","TRUE","1"].includes(String(value??"").trim().toUpperCase());}
async function topCacheStatus(env){const{results=[]}=await env.DB.prepare(`SELECT c.rank,c.track_id,c.storage_key,t.title,t.artist,t.play_count FROM top_played_cache c JOIN tracks t ON t.id=c.track_id ORDER BY c.rank ASC LIMIT 200`).all();return{filled:results.length,limit:200,complete:results.length===200,items:results};}
async function seed(env,req){
 if(!(await auth(env,req)))return json({error:"Authentication required"},401);
 let body;try{body=await req.json();}catch{return json({error:"Invalid JSON body"},400);}
 const items=Array.isArray(body?.items)?body.items.filter(x=>x?.title):[];if(!items.length)return json({error:"No tracks supplied"},400);
 await env.DB.prepare(`UPDATE tracks SET play_count=0`).run();await env.DB.prepare(`DELETE FROM playlist_entries`).run();await env.DB.prepare(`DELETE FROM top_played_cache`).run();
 for(let offset=0;offset<items.length;offset+=150){const chunk=items.slice(offset,offset+150);await env.DB.batch(chunk.map((x,i)=>{const sourceId=x.source_id?`apple:${String(x.source_id)}`:null;const sourceUrl=x.source_url||(x.source_id?`https://music.apple.com/us/song/${slug(x.title)}/${String(x.source_id)}`:null);return env.DB.prepare(`INSERT OR IGNORE INTO tracks (source,source_id,source_url,title,artist,album,duration_ms,isrc,artwork_url,natural_key,play_count) VALUES ('apple',?,?,?,?,?,?,?,?,?,0)`).bind(sourceId,sourceUrl,x.title,x.artist||"",x.album||null,Number(x.duration_ms)||null,x.isrc||null,x.artwork_url||null,naturalKey(x,offset+i));}));}
 const{results:sourceRows=[]}=await env.DB.prepare(`SELECT id,source_id,title FROM tracks WHERE source='apple' AND (source_url IS NULL OR source_url='') AND source_id IS NOT NULL`).all();
 for(let offset=0;offset<sourceRows.length;offset+=100){const chunk=sourceRows.slice(offset,offset+100);await env.DB.batch(chunk.map(t=>env.DB.prepare(`UPDATE tracks SET source_url=? WHERE id=?`).bind(`https://music.apple.com/us/song/${slug(t.title)}/${String(t.source_id).replace(/^apple:/,"")}`,t.id)));}
 const playlistRows=[];for(let offset=0;offset<items.length;offset+=100){const chunk=items.slice(offset,offset+100).filter(x=>x.source_id);if(!chunk.length)continue;const placeholders=chunk.map(()=>"?").join(",");const ids=chunk.map(x=>`apple:${String(x.source_id)}`);const{results=[]}=await env.DB.prepare(`SELECT id,source_id,title,artist,album,artwork_url,duration_ms FROM tracks WHERE source_id IN (${placeholders})`).bind(...ids).all();const bySource=new Map(results.map(r=>[r.source_id,r]));for(const x of chunk){const t=bySource.get(`apple:${String(x.source_id)}`);if(t)playlistRows.push(t);}}
 const byKey=new Map(playlistRows.map(t=>[t.source_id||`title:${t.title}|artist:${t.artist}|album:${t.album||""}`,t]));const ordered=[];for(let i=0;i<items.length;i++){const x=items[i];const key=x.source_id?`apple:${String(x.source_id)}`:`title:${x.title}|artist:${x.artist||""}|album:${x.album||""}`;const t=byKey.get(key);if(t&&!ordered.some(o=>o.id===t.id))ordered.push(t);}
 for(let offset=0;offset<ordered.length;offset+=150){const chunk=ordered.slice(offset,offset+150);await env.DB.batch(chunk.map((t,i)=>env.DB.prepare(`INSERT INTO playlist_entries(track_id,position,title,artist,album,artwork_url,duration_ms) VALUES(?,?,?,?,?,?,?)`).bind(t.id,offset+i+1,t.title,t.artist,t.album,t.artwork_url,t.duration_ms)));}
 const topItems=items.filter(isTopCacheRow).slice(0,200);const topTracks=[];for(const x of topItems){const t=x.source_id?await env.DB.prepare(`SELECT id,title,artist FROM tracks WHERE source_id=?`).bind(`apple:${String(x.source_id)}`).first():await env.DB.prepare(`SELECT id,title,artist FROM tracks WHERE natural_key=?`).bind(naturalKey(x,items.indexOf(x))).first();if(t&&!topTracks.some(v=>v.id===t.id))topTracks.push(t);}if(topTracks.length)await env.DB.batch(topTracks.map((t,i)=>env.DB.prepare(`INSERT INTO top_played_cache(rank,track_id,storage_key,updated_at) VALUES(?,?,NULL,CURRENT_TIMESTAMP)`).bind(i+1,t.id)));
 const{results:missing=[]}=await env.DB.prepare(`SELECT COUNT(*) AS count FROM tracks WHERE duration_ms IS NULL OR duration_ms<=0 OR artwork_url IS NULL OR artwork_url=''`).all();const missingCount=Number(missing[0]?.count||0);
 return json({ok:true,build:"v3-excel-top-cache",playlist_entries:ordered.length,cache_entries:topTracks.length,cache_limit:200,top100:topTracks.map((t,i)=>({rank:i+1,track_id:t.id,title:t.title,artist:t.artist,play_count:0})),missing_count:items.length-ordered.length,metadata_missing_after_seed:missingCount,play_counts_reset:true,metadata_backfill:{deferred:true,batch_limit:20,remaining:missingCount}});
}
export async function handleLibraryV3(req,env){const url=new URL(req.url);if(url.pathname==="/api/v1/library/seed"&&req.method==="POST")return seed(env,req);if(url.pathname==="/api/v1/cache/top/status"&&req.method==="GET"){if(!(await auth(env,req)))return json({error:"Authentication required"},401);return json({ok:true,cache:await topCacheStatus(env)});}return null;}
