const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store, no-cache, must-revalidate"}});
async function sha256(text){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function cookie(req){return(req.headers.get("Cookie")||"").match(/(?:^|;\s*)music_session=([^;]+)/)?.[1]||null;}
async function auth(env,req){const token=cookie(req);if(!token||!env.DB)return null;const hash=await sha256(token);const row=await env.DB.prepare(`SELECT id_hash FROM sessions WHERE id_hash=? AND expires_at>?`).bind(hash,Math.floor(Date.now()/1000)).first();return row?hash:null;}
function sourceLabel(mode){if(mode==="album")return "Album";if(mode==="playlist")return "Playlist";if(mode==="search")return "Search";return "Queue";}
async function snapshot(env,user){
  const r=await env.DB.prepare(`
    SELECT q.position,q.track_id,t.title,t.artist,t.album,t.artwork_url,t.duration_ms,t.source,t.source_id,t.source_url,t.isrc,
      CASE WHEN gc.track_id IS NOT NULL OR tc.track_id IS NOT NULL OR ac.track_id IS NOT NULL THEN 1 ELSE 0 END AS server_cached,
      CASE WHEN gc.track_id IS NOT NULL THEN 1 ELSE 0 END AS general_cached,
      CASE WHEN tc.track_id IS NOT NULL THEN 1 ELSE 0 END AS top_cached,
      CASE WHEN ac.track_id IS NOT NULL THEN 1 ELSE 0 END AS album_cached
    FROM queue_entries q
    JOIN tracks t ON t.id=q.track_id
    LEFT JOIN general_cache gc ON gc.track_id=q.track_id
    LEFT JOIN top_played_cache tc ON tc.track_id=q.track_id
    LEFT JOIN album_cache ac ON ac.track_id=q.track_id AND ac.status='complete'
    WHERE q.user_key=?
    ORDER BY q.position ASC`).bind(user).all();
  const state=await env.DB.prepare(`SELECT current_index,mode FROM queue_state WHERE user_key=?`).bind(user).first();
  const mode=state?.mode||"manual";
  return {items:(r.results||[]).map(x=>({...x,queue_source:sourceLabel(mode),server_available:Number(x.server_cached||0)===1,cache_sources:[...(Number(x.general_cached||0)?["general"]:[]),...(Number(x.top_cached||0)?["top"]:[]),...(Number(x.album_cached||0)?["album"]:[])]})),current_index:Number(state?.current_index??-1),mode};
}
function cleanItems(items){const seen=new Set();return(items||[]).map(x=>({...x,track_id:Number(x.track_id??x.id)})).filter(x=>Number.isInteger(x.track_id)&&x.track_id>0&&!seen.has(x.track_id)&&seen.add(x.track_id));}
async function rewrite(env,user,items,currentIndex,mode){await env.DB.prepare(`DELETE FROM queue_entries WHERE user_key=?`).bind(user).run();for(let offset=0;offset<items.length;offset+=50){const chunk=items.slice(offset,offset+50);await env.DB.batch(chunk.map((x,i)=>env.DB.prepare(`INSERT INTO queue_entries(user_key,position,track_id) VALUES(?,?,?)`).bind(user,offset+i,x.track_id)));}await env.DB.prepare(`INSERT OR REPLACE INTO queue_state(user_key,current_index,mode,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP)`).bind(user,items.length?Math.max(0,Math.min(currentIndex,items.length-1)):-1,mode||"manual").run();return snapshot(env,user);}
export async function handleQueue(req,env){const url=new URL(req.url);const m=url.pathname.match(/^\/api\/v1\/(?:playback-queue|queue)(?:\/(\d+))?$/);if(!m)return null;const user=await auth(env,req);if(!user)return json({error:"Authentication required"},401);const index=m[1]==null?null:Number(m[1]);if(req.method==="GET")return json(await snapshot(env,user));if(req.method==="DELETE"&&!m[1])return json(await rewrite(env,user,[],-1,"manual"));if(req.method==="DELETE"&&index!=null){const s=await snapshot(env,user);if(index<0||index>=s.items.length)return json({error:"Queue index out of range"},400);const items=s.items.filter((_,i)=>i!==index);let cur=s.current_index;if(cur===index)cur=Math.min(index,items.length-1);else if(cur>index)cur--;return json(await rewrite(env,user,items,cur,s.mode));}if(req.method==="POST"&&!m[1]){const body=await req.json().catch(()=>({}));let items=cleanItems(body.items);const mode=body.playback_mode||"manual";let current=Number.isInteger(body.current_index)?body.current_index:0;if((mode==="playlist"||mode==="album")&&items.length){const sourceId=body.source_track_id!=null?Number(body.source_track_id):null;const sourceIndex=sourceId!=null?items.findIndex(x=>x.track_id===sourceId):current;if(sourceIndex>0){items=items.slice(sourceIndex);current=0;}else if(sourceIndex===0){current=0;}}if(body.mode==="append"){const s=await snapshot(env,user);const merged=cleanItems([...s.items,...items]);return json(await rewrite(env,user,merged,s.current_index,s.mode));}return json(await rewrite(env,user,items,current,mode));}return json({error:"Method not allowed"},405);}
export async function handleQueueReorder(req,env){if(!["/api/v1/playback-queue/reorder","/api/v1/queue/reorder"].includes(new URL(req.url).pathname)||req.method!=="POST")return null;const user=await auth(env,req);if(!user)return json({error:"Authentication required"},401);const body=await req.json().catch(()=>({}));const from=Number(body.from),to=Number(body.to);const s=await snapshot(env,user);if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0||from>=s.items.length||to>=s.items.length)return json({error:"Invalid queue positions"},400);const items=[...s.items];const[moved]=items.splice(from,1);items.splice(to,0,moved);let cur=s.current_index;if(cur===from)cur=to;else if(from<cur&&cur<=to)cur--;else if(to<=cur&&cur<from)cur++;return json(await rewrite(env,user,items,cur,s.mode));}
export async function handleQueueCurrent(req,env){if(!["/api/v1/playback-queue/current","/api/v1/queue/current"].includes(new URL(req.url).pathname)||req.method!=="POST")return null;const user=await auth(env,req);if(!user)return json({error:"Authentication required"},401);const body=await req.json().catch(()=>({}));const s=await snapshot(env,user);const idx=Number(body.index);if(!Number.isInteger(idx)||idx<0||idx>=s.items.length)return json({error:"Invalid queue index"},400);await env.DB.prepare(`UPDATE queue_state SET current_index=?,updated_at=CURRENT_TIMESTAMP WHERE user_key=?`).bind(idx,user).run();return json(await snapshot(env,user));}
