name = "dakshmusic3"
main = "worker.js"
compatibility_date = "2026-07-01"
account_id = "ed9504226c687dce2353fbc23a1d5890"
workers_dev = true

[vars]
ENVIRONMENT = "production"
GENERAL_CACHE_LIMIT = "25"
MAX_ALBUM_SESSIONS = "5"
DEVICE_CACHE_LIMIT = "10"
DEEZER_API = "https://api.deezer.com"

[[d1_databases]]
binding = "DB"
database_name = "dakshmusic3"
database_id = "abf08c50-9533-4e91-8fe9-8c0b72f28136"

[assets]
directory = "../frontend"
binding = "ASSETS"
