name = "dakshmusic3"
main = "app.js"
compatibility_date = "2026-07-01"
account_id = "ed9504226c687dce2353fbc23a1d5890"
workers_dev = true

[vars]
ENVIRONMENT = "production"
GENERAL_CACHE_LIMIT = "200"
MAX_ALBUM_SESSIONS = "5"
DEVICE_CACHE_LIMIT = "10"
DEEZER_API = "https://api.deezer.com"
GITHUB_OWNER = "dloiya"
GITHUB_REPO = "dakshmusic3"

[[d1_databases]]
binding = "DB"
database_name = "dakshmusic3"
database_id = "abf08c50-9533-4e91-8fe9-8c0b72f28136"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "dakshmusic3-audio"

[assets]
directory = "../frontend"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
