import legacy from "./index.js";
import { getInstance, instanceAction } from "./oci.js";

const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };
const now = () => new Date().toISOString();
function corsHeaders(request){const origin=request.headers.get("Origin");return{"access-control-allow-origin":origin||"*","access-control-allow-methods":"GET,POST,DELETE,OPTIONS","access-control-allow-headers":"Content-Type, Authorization","access-control-max-age":"86400",vary:"Origin"};}
function json(data,status=200,request=null,extra={}){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...(request?corsHeaders(request):{}),...extra}});}
function error(request,message,status=400){return json({error:message},status,request);}
function ociBase(env){const value=env.OCI_API_URL?.trim();if(!value)throw new Error("OCI_API_URL is not configured");return value.replace(/\/$/,"");}
async function ociRequest(request,env,path,init={}){if(!env.OCI_API_TOKEN)throw new Error("OCI_API_TOKEN is not configured");const headers=new Headers(init.headers||{});headers.set("Authorization",`Bearer ${env.OCI_API_TOKEN}`);headers.set("Accept","application/json");const upstream=await fetch(`${ociBase(env)}${path}`,{...init,headers});const text=await upstream.text();let data;try{data=JSON.parse(text);}catch{data={detail:text||`OCI returned HTTP ${upstream.status}`};}return json(data,upstream.status,request);}
async function callRetriever(env,jobId,track,priority="normal"){
  const url=track?.source_url;
  if(!url)throw new Error("Track has no source_url");
  if(!env.OCI_API_TOKEN)throw new Error("OCI_API_TOKEN is not configured");
  const encoded=encodeURIComponent(url);
  const headers={Authorization:`Bearer ${env.OCI_API_TOKEN}`,Accept:"application/json","Content-Type":"application/json"};
  const upstream=await fetch(`${ociBase(env)}/acquire/${encoded}`,{method:"POST",headers,body:JSON.stringify({job_id:jobId,track_id:Number(track.id),source_url:url,title:track.title,artist:track.artist,album_name:track.album_name||null,priority})});
  const text=await upstream.text();
  let data={};
  try{data=JSON.parse(text);}catch{data={detail:text};}
  return {ok:upstream.ok,status:upstream.status,data};
}
async function ensureAcquisition(env,trackId,priority="normal",ctx=null){
  const track=await env.DB.prepare(`SELECT id,title,artist,album_name,source_url,storage_key,storage_status FROM tracks WHERE id=?`).bind(Number(trackId)).first();
  if(!track)return null;
  if(track.storage_status==="ready"&&track.storage_key)return {ready:true,track_id:Number(track.id)};
  const active=await env.DB.prepare(`SELECT id,status FROM acquisition_jobs WHERE track_id=? AND status IN ('queued','running') ORDER BY created_at DESC LIMIT 1`).bind(Number(trackId)).first();
  if(active)return {job_id:active.id,status:active.status,duplicate:true};
  const jid=crypto.randomUUID(),t=now();
  await env.DB.prepare(`INSERT INTO acquisition_jobs(id,track_id,status,worker,attempts,error,created_at,updated_at,started_at) VALUES(?,?, 'queued','oci',0,NULL,?,?,NULL)`).bind(jid,Number(trackId),t,t).run();
  const run=async()=>{
    try{
      await env.DB.prepare(`UPDATE acquisition_jobs SET status='running',worker='oci',attempts=attempts+1,started_at=?,updated_at=?,error=NULL WHERE id=?`).bind(now(),now(),jid).run();
      const result=await callRetriever(env,jid,track,priority);
      if(!result.ok)throw new Error(result.data?.detail||result.data?.error||`OCI retriever returned HTTP ${result.status}`);
      const d=result.data||{};
      const storageKey=d.storage_key||d.key||d.r2_key||null;
      const status=["ready","completed","complete","success"].includes(String(d.status||"").toLowerCase())||!!storageKey?"completed":"running";
      await env.DB.prepare(`UPDATE acquisition_jobs SET status=?,updated_at=?,completed_at=?,error=NULL WHERE id=?`).bind(status,now(),status==="completed"?now():null,jid).run();
      if(storageKey){
        await env.DB.prepare(`UPDATE tracks SET storage_key=?,storage_status='ready',cache_requested=1,updated_at=? WHERE id=?`).bind(String(storageKey),now(),Number(track.id)).run();
      }else if(status==="completed"){
        await env.DB.prepare(`UPDATE tracks SET storage_status='ready',cache_requested=1,updated_at=? WHERE id=?`).bind(now(),Number(track.id)).run();
      }else{
        await env.DB.prepare(`UPDATE tracks SET storage_status='downloading',cache_requested=1,updated_at=? WHERE id=?`).bind(now(),Number(track.id)).run();
      }
    }catch(e){
      console.error("OCI retriever job failed",jid,e);
      await env.DB.prepare(`UPDATE acquisition_jobs SET status='failed',updated_at=?,completed_at=?,error=? WHERE id=?`).bind(now(),now(),String(e?.message||e),jid).run();
      await env.DB.prepare(`UPDATE tracks SET storage_status='failed',updated_at=? WHERE id=?`).bind(now(),Number(track.id)).run();
    }
  };
  if(ctx)ctx.waitUntil(run());else await run();
  return {job_id:jid,status:"queued",track_id:Number(track.id),priority};
}
async function deezerSearch(request){const u=new URL(request.url),q=u.searchParams.get("q")?.trim(),limit=Math.min(Math.max(Number(u.searchParams.get("limit")||25),1),50);if(!q)return error(request,"Missing q");const d=new URL("https://api.deezer.com/search");d.searchParams.set("q",q);d.searchParams.set("limit",String(limit));const r=await fetch(d,{headers:{accept:"application/json"}});if(!r.ok)return error(request,`Deezer search failed: HTTP ${r.status}`,502);const data=await r.json();if(data?.error)return error(request,data.error.message||"Deezer search failed",502);return json(data,200,request,{"cache-control":"public, max-age=60, s-maxage=300"});}
async function ensureHistory(db){await db.prepare(`CREATE TABLE IF NOT EXISTS album_play_history (id INTEGER PRIMARY KEY AUTOINCREMENT, album_id INTEGER NOT NULL, album_name TEXT, artist TEXT, artwork_url TEXT, played_at TEXT NOT NULL)`).run();}
async function upsertTrack(db,t){if(!t?.title||!t?.artist||!t?.source||!t?.source_id||!t?.source_url)throw new Error("title, artist, source, source_id and source_url are required");const v=[String(t.title),String(t.artist),t.album_id==null?null:Number(t.album_id),t.album_name||null,String(t.source),String(t.source_id),String(t.source_url),t.isrc||null,t.duration_ms==null?null:Number(t.duration_ms),t.artwork_url||null,t.metadata_json?JSON.stringify(t.metadata_json):null],e=await db.prepare(`SELECT id FROM tracks WHERE source=? AND source_id=? LIMIT 1`).bind(v[4],v[5]).first(),ts=now();if(e){await db.prepare(`UPDATE tracks SET title=?,artist=?,album_id=?,album_name=?,source_url=?,isrc=?,duration_ms=?,artwork_url=?,metadata_json=?,updated_at=? WHERE id=?`).bind(v[0],v[1],v[2],v[3],v[6],v[7],v[8],v[9],v[10],ts,e.id).run();return Number(e.id);}const r=await db.prepare(`INSERT INTO tracks(title,artist,album_id,album_name,source,source_id,source_url,isrc,duration_ms,artwork_url,storage_status,play_count,cache_requested,created_at,updated_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?, 'missing',0,0,?,?,?)`).bind(...v.slice(0,10),ts,ts,v[10]).run();return Number(r.meta.last_row_id);}
async function trackRows(db,limit=2000){const r=await db.prepare(`SELECT id,title,artist,album_id,album_name,source,source_id,source_url,isrc,duration_ms,artwork_url,storage_key,storage_status,play_count,cache_requested,created_at,updated_at,metadata_json FROM tracks ORDER BY artist,title LIMIT ?`).bind(limit).all();return r.results||[];}
async function albumRows(db,id){const r=await db.prepare(`SELECT id,title,artist,album_id,album_name,source,source_id,source_url,isrc,duration_ms,artwork_url,storage_key,storage_status,play_count,cache_requested,created_at,updated_at,metadata_json FROM tracks WHERE album_id=? ORDER BY id`).bind(Number(id)).all();return r.results||[];}
async function albumList(db,limit=1000){const r=await db.prepare(`SELECT album_id AS id,album_name AS title,MAX(artist) AS artist,MAX(artwork_url) AS artwork_url,COUNT(*) AS track_count,MAX(updated_at) AS updated_at FROM tracks WHERE album_id IS NOT NULL GROUP BY album_id,album_name ORDER BY artist,album_name LIMIT ?`).bind(limit).all();return r.results||[];}
async function playlistRows(db){const r=await db.prepare(`SELECT p.id AS playlist_entry_id,p.position,t.id,t.title,t.artist,t.album_id,t.album_name,t.source,t.source_id,t.source_url,t.isrc,t.duration_ms,t.artwork_url,t.storage_key,t.storage_status,t.play_count,t.metadata_json FROM playlist_entries p JOIN tracks t ON t.id=p.track_id ORDER BY p.position,p.id`).all();return r.results||[];}
async function queueRows(db,key){const r=await db.prepare(`SELECT q.id AS queue_entry_id,q.position,t.id,t.title,t.artist,t.album_id,t.album_name,t.source,t.source_id,t.source_url,t.artwork_url,t.duration_ms,t.storage_key,t.storage_status,t.play_count,t.metadata_json FROM queue_entries q JOIN tracks t ON t.id=q.track_id WHERE q.queue_key=? ORDER BY q.position`).bind(key).all();return r.results||[];}
async function setMode(db,mode){const t=now();await db.prepare(`INSERT INTO queue_state(queue_key,current_index,mode,shuffle_enabled,updated_at) VALUES('default',0,?,1,?) ON CONFLICT(queue_key) DO UPDATE SET current_index=0,mode=excluded.mode,updated_at=excluded.updated_at`).bind(mode,t).run();}
async function clearKey(db,key){await db.prepare(`DELETE FROM queue_entries WHERE queue_key=?`).bind(key).run();}
function csvEscape(v){const s=v==null?"":String(v);return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function toCsv(rows){const c=["id","title","artist","album_id","album_name","source","source_id","source_url","isrc","duration_ms","artwork_url","storage_key","storage_status","play_count","cache_requested","created_at","updated_at"];return[c.join(","),...rows.map(r=>c.map(k=>csvEscape(r[k])).join(","))].join("\n");}
function parseCsv(text){const lines=String(text||"").replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const parse=s=>{const a=[];let x="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(x);x="";}else x+=c;}a.push(x);return a;};const h=parse(lines[0]);return lines.slice(1).map(l=>{const v=parse(l),o={};h.forEach((k,i)=>o[k]=v[i]??"");return o;});}
export async function watchdog(env,reason="scheduled"){if(env.OCI_API_URL&&env.OCI_API_TOKEN){const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{const r=await fetch(`${ociBase(env)}/health`,{headers:{Authorization:`Bearer ${env.OCI_API_TOKEN}`,Accept:"application/json"},signal:c.signal,cache:"no-store"});if(r.ok)return{status:"healthy",action:"none",reason};}catch{}finally{clearTimeout(timer);}}const instance=await getInstance(env),state=instance?.lifecycleState;if(state==="STOPPED"){await instanceAction(env,"START");return{status:"recovering",action:"START",lifecycleState:state,reason};}if(state==="STARTING"||state==="STOPPING")return{status:"waiting",action:"none",lifecycleState:state,reason};if(state==="RUNNING"){await instanceAction(env,"RESET");return{status:"recovering",action:"RESET",lifecycleState:state,reason};}return{status:"waiting",action:"none",lifecycleState:state,reason};}
async function handle(request,env,ctx){const url=new URL(request.url),path=url.pathname.replace(/\/+$/g,"")||"/",method=request.method.toUpperCase();if(method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(request)});try{
if(path==="/api/health"&&method==="GET"){await env.DB.prepare("SELECT 1 AS ok").first();return json({ok:true,service:"dakshmusic3"},200,request);}
if(path==="/api/search"&&method==="GET")return deezerSearch(request);
if(path==="/api/watchdog"&&method==="POST")return json(await watchdog(env,"manual"),200,request);
if(path==="/api/start"&&method==="POST")return ociRequest(request,env,"/start",{method:"POST"});
if(path==="/api/library/tracks"&&method==="GET"){const n=Math.min(Math.max(Number(url.searchParams.get("limit")||500),1),2000);return json({tracks:await trackRows(env.DB,n)},200,request);}
if(path==="/api/library/albums"&&method==="GET"){const n=Math.min(Math.max(Number(url.searchParams.get("limit")||500),1),1000);return json({albums:await albumList(env.DB,n)},200,request);}
const am=path.match(/^\/api\/library\/albums\/(\d+)$/);if(am&&method==="GET"){const rows=await albumRows(env.DB,am[1]);if(!rows.length)return error(request,"Album not found",404);return json({album:{id:Number(am[1]),title:rows[0].album_name,artist:rows[0].artist,artwork_url:rows[0].artwork_url,track_count:rows.length},tracks:rows},200,request);}
if(path==="/api/tracks/resolve"&&method==="POST"){const id=await upsertTrack(env.DB,await request.json());return json({ok:true,track_id:id},200,request);}
if(path==="/api/playlist"&&method==="GET")return json({name:"default",tracks:await playlistRows(env.DB)},200,request);
if(path==="/api/playlist"&&method==="POST"){const b=await request.json(),id=Number(b.track_id);if(!id)return error(request,"track_id is required");const d=await env.DB.prepare(`SELECT id,position FROM playlist_entries WHERE track_id=? LIMIT 1`).bind(id).first();if(d)return json({ok:true,duplicate:true,id:Number(d.id),position:Number(d.position)},200,request);const m=await env.DB.prepare(`SELECT COALESCE(MAX(position),-1) p FROM playlist_entries`).first(),p=Number(m?.p??-1)+1,t=now(),r=await env.DB.prepare(`INSERT INTO playlist_entries(track_id,position,added_at,updated_at) VALUES(?,?,?,?)`).bind(id,p,t,t).run();return json({ok:true,id:Number(r.meta.last_row_id),position:p},201,request);}
const pr=path.match(/^\/api\/playlist\/(\d+)$/);if(pr&&method==="DELETE"){await env.DB.prepare(`DELETE FROM playlist_entries WHERE id=?`).bind(Number(pr[1])).run();return json({ok:true},200,request);}
if(path==="/api/playback/mode"&&method==="POST"){const b=await request.json();if(!["track","album"].includes(b.mode))return error(request,"mode must be track or album");await clearKey(env.DB,"album-current");if(b.mode==="track")await clearKey(env.DB,"default");await setMode(env.DB,b.mode);return json({ok:true,mode:b.mode},200,request);}
if(path==="/api/play/track"&&method==="POST"){const b=await request.json(),id=Number(b.track_id);if(!id)return error(request,"track_id is required");await clearKey(env.DB,"album-current");await setMode(env.DB,"track");await env.DB.prepare(`UPDATE tracks SET play_count=COALESCE(play_count,0)+1,updated_at=? WHERE id=?`).bind(now(),id).run();const acquisition=await ensureAcquisition(env,id,"high",ctx);return json({ok:true,mode:"track",track_id:id,acquisition},200,request);}
const pa=path.match(/^\/api\/play\/album\/(\d+)$/);if(pa&&method==="POST"){const id=Number(pa[1]),rows=await albumRows(env.DB,id);if(!rows.length)return error(request,"Album not found",404);await ensureHistory(env.DB);await clearKey(env.DB,"default");await clearKey(env.DB,"album-current");await setMode(env.DB,"album");const t=now();await env.DB.prepare(`INSERT INTO album_play_history(album_id,album_name,artist,artwork_url,played_at) VALUES(?,?,?,?,?)`).bind(id,rows[0].album_name,rows[0].artist,rows[0].artwork_url,t).run();await env.DB.prepare(`DELETE FROM album_play_history WHERE id NOT IN (SELECT id FROM album_play_history ORDER BY played_at DESC LIMIT 5)`).run();for(let i=0;i<rows.length;i++)await env.DB.prepare(`INSERT INTO queue_entries(queue_key,track_id,position,added_at,updated_at) VALUES('album-current',?,?,?,?)`).bind(rows[i].id,i,t,t).run();const jobs=[];for(let i=0;i<rows.length;i++){if(rows[i].storage_status!=="ready")jobs.push(await ensureAcquisition(env,rows[i].id,i===0?"high":"normal",ctx));}return json({ok:true,mode:"album",album_id:id,tracks:rows,acquisition_jobs:jobs},200,request);}
if(path==="/api/albums/history"&&method==="GET"){await ensureHistory(env.DB);const r=await env.DB.prepare(`SELECT album_id,album_name AS title,artist,artwork_url,played_at FROM album_play_history ORDER BY played_at DESC LIMIT 5`).all();return json({albums:r.results||[]},200,request);}
if(path==="/api/queue"&&method==="GET"){const key=url.searchParams.get("queue_key")||"default",state=await env.DB.prepare(`SELECT queue_key,current_index,mode,shuffle_enabled,updated_at FROM queue_state WHERE queue_key=?`).bind(key).first();return json({queue_key:key,state:state||{queue_key:key,current_index:0,mode:key==="album-current"?"album":"track",shuffle_enabled:1},tracks:await queueRows(env.DB,key)},200,request);}
if(path==="/api/queue/next"&&method==="POST"){const b=await request.json().catch(()=>({})),key=b.queue_key||"default",rows=await queueRows(env.DB,key),state=await env.DB.prepare(`SELECT current_index,mode,shuffle_enabled FROM queue_state WHERE queue_key=?`).bind(key).first(),next=rows.length?(Number(state?.current_index||0)+1)%rows.length:0,t=now();await env.DB.prepare(`INSERT INTO queue_state(queue_key,current_index,mode,shuffle_enabled,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(queue_key) DO UPDATE SET current_index=excluded.current_index,updated_at=excluded.updated_at`).bind(key,next,state?.mode||"track",Number(state?.shuffle_enabled??1),t).run();return json({ok:true,current_index:next,track:rows[next]||null},200,request);}
if(path==="/api/export/tracks.csv"&&method==="GET")return new Response(toCsv(await trackRows(env.DB,2000)),{status:200,headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=tracks.csv",...corsHeaders(request)}});
if(path==="/api/import/tracks.csv"&&method==="POST"){const rows=parseCsv(await request.text());let imported=0;for(const r of rows){if(!r.title||!r.artist||!r.source||!r.source_id||!r.source_url)continue;await upsertTrack(env.DB,{...r,album_id:r.album_id?Number(r.album_id):null,duration_ms:r.duration_ms?Number(r.duration_ms):null});imported++;}return json({ok:true,imported},200,request);}
if(path==="/api/data/delete"&&method==="POST"){const b=await request.json();if(b.confirm!=="DELETE")return error(request,"Confirmation required: DELETE");await env.DB.batch([env.DB.prepare(`DELETE FROM playlist_entries`),env.DB.prepare(`DELETE FROM queue_entries`),env.DB.prepare(`DELETE FROM queue_state`),env.DB.prepare(`DELETE FROM acquisition_jobs`),env.DB.prepare(`DELETE FROM cache_objects`),env.DB.prepare(`DELETE FROM tracks`),env.DB.prepare(`DELETE FROM album_play_history`)]);return json({ok:true},200,request);}
const acquire=path.match(/^\/api\/acquire\/(.+)$/);if(acquire&&method==="POST"){return ociRequest(request,env,`/acquire/${acquire[1]}`,{method:"POST",body:request.body,headers:{"Content-Type":request.headers.get("Content-Type")||"application/json"}});}
if(path==="/api/acquisition"&&method==="GET"){const n=Math.min(Math.max(Number(url.searchParams.get("limit")||20),1),100);const r=await env.DB.prepare(`SELECT a.id,a.track_id,a.status,a.worker,a.attempts,a.error,a.created_at,a.updated_at,a.started_at,a.completed_at,t.title,t.artist,t.source_url FROM acquisition_jobs a JOIN tracks t ON t.id=a.track_id ORDER BY a.created_at DESC LIMIT ?`).bind(n).all();return json({jobs:r.results||[]},200,request);}
if(path==="/api/acquisition"&&method==="POST"){const b=await request.json(),id=Number(b.track_id);if(!id)return error(request,"track_id is required");const acquisition=await ensureAcquisition(env,id,b.priority||"normal",ctx);if(!acquisition)return error(request,"Track not found",404);return json({ok:true,...acquisition},202,request);}
return legacy.fetch(request,env,ctx);
}catch(e){console.error(e);return error(request,e?.message||"Internal error",500);}}
export default{async fetch(request,env,ctx){return handle(request,env,ctx);},async queue(batch,env,ctx){for(const message of batch.messages){console.log("Processing metadata message:",message.body);message.ack();}},async scheduled(controller,env,ctx){ctx.waitUntil(watchdog(env,`cron:${controller.cron}`).catch(e=>console.error("Scheduled OCI watchdog failed",e)));}};
