import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const API=import.meta.env.VITE_QUEUE_API_URL?.replace(/\/$/,"")||"";
const request=async(path,options={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{...(options.body?{"Content-Type":options.headers?.["Content-Type"]||"application/json"}:{}),...(options.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`API error ${r.status}`)}return r};
const json=async(path,options={})=>(await request(path,options)).json();
const deezerTrack=x=>({title:x.title,artist:x.artist?.name||"Unknown artist",album_id:x.album?.id??null,album_name:x.album?.title??null,source:"deezer",source_id:String(x.id),source_url:`https://www.deezer.com/track/${x.id}`,artwork_url:x.album?.cover_xl||x.album?.cover_medium||null,duration_ms:Number(x.duration||0)*1000,metadata_json:{deezer:x}});
const MENU=["Now Playing","Playlist","Search","Album","Queue","Settings"];

function App(){
 const[windowName,setWindowName]=useState("home"),[menuIndex,setMenuIndex]=useState(0),[mode,setMode]=useState("track"),[current,setCurrent]=useState(null),[playlist,setPlaylist]=useState([]),[albums,setAlbums]=useState([]),[history,setHistory]=useState([]),[queue,setQueue]=useState([]),[results,setResults]=useState([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[settingsTab,setSettingsTab]=useState("params"),[busy,setBusy]=useState(false),audio=useRef(null),upload=useRef(null),wheelStart=useRef(null);
 const refresh=async()=>{try{const[p,a,h]=await Promise.all([json("/api/playlist"),json("/api/library/albums?limit=1000"),json("/api/albums/history")]);setPlaylist(p.tracks||[]);setAlbums(a.albums||[]);setHistory(h.albums||[])}catch(e){setMessage(e.message)}};
 const refreshQueue=async()=>{try{const key=mode==="album"?"album-current":"default",d=await json(`/api/queue?queue_key=${key}`);setQueue(d.tracks||[])}catch(e){setMessage(e.message)}};
 useEffect(()=>{refresh();refreshQueue()},[]);useEffect(()=>{refreshQueue()},[mode]);
 const open=name=>{setWindowName(name);setMenuIndex(Math.max(0,MENU.indexOf(name)))};
 const home=()=>setWindowName("home");
 const moveMenu=d=>setMenuIndex(i=>(i+d+MENU.length)%MENU.length);
 const selectMenu=index=>open(MENU[index??menuIndex]);
 const handleWheelPointerDown=e=>{if(e.pointerType==="mouse"&&e.button!==0)return;wheelStart.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId)};
 const handleWheelPointerUp=e=>{const s=wheelStart.current;if(!s)return;wheelStart.current=null;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.abs(dy)>24&&Math.abs(dy)>Math.abs(dx)){moveMenu(dy>0?-1:1);return}if(Math.abs(dx)>24&&Math.abs(dx)>Math.abs(dy)&&windowName!=="home"){dx>0?home():open("Now Playing");return}if(windowName==="home"&&Math.abs(dx)<24&&Math.abs(dy)<24)selectMenu()};
 const switchMode=async(next)=>{if(next===mode)return true;if(!confirm(`Move device to ${next} mode?\nThe current playback session will be replaced.`))return false;try{await json("/api/playback/mode",{method:"POST",body:JSON.stringify({mode:next})});setMode(next);setCurrent(null);setQueue([]);setMessage(`${next.toUpperCase()} MODE`);return true}catch(e){setMessage(e.message);return false}};
 const playTrack=async(track)=>{if(!(await switchMode("track")))return;try{setBusy(true);const r=track.id?{track_id:track.id}:await json("/api/tracks/resolve",{method:"POST",body:JSON.stringify(track)});const id=r.track_id||r.id;await json("/api/play/track",{method:"POST",body:JSON.stringify({track_id:id})});setCurrent({...track,id});open("Now Playing");setTimeout(()=>audio.current?.play().catch(()=>{}),50);await refresh();await refreshQueue()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const playAlbum=async(album)=>{if(!(await switchMode("album")))return;try{setBusy(true);const d=await json(`/api/play/album/${album.id}`,{method:"POST"});setCurrent(d.tracks?.[0]||null);open("Now Playing");setMessage(`ALBUM · ${album.title}`);await refresh();await refreshQueue();setTimeout(()=>audio.current?.play().catch(()=>{}),50)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const next=async()=>{const rows=queue.length?queue:playlist;if(!rows.length)return;const i=Math.max(0,rows.findIndex(x=>x.id===current?.id));await playTrack(rows[(i+1)%rows.length])};
 const search=async e=>{e.preventDefault();if(!query.trim())return;try{setBusy(true);const d=await json(`/api/search?q=${encodeURIComponent(query.trim())}&limit=25`);setResults(d.data||[])}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const add=async x=>{try{const t=deezerTrack(x),r=await json("/api/tracks/resolve",{method:"POST",body:JSON.stringify(t)});await json("/api/playlist",{method:"POST",body:JSON.stringify({track_id:r.track_id})});setMessage(`ADDED · ${t.title}`);await refresh()}catch(e){setMessage(e.message)}};
 const remove=async id=>{try{await request(`/api/playlist/${id}`,{method:"DELETE"});await refresh()}catch(e){setMessage(e.message)}};
 const exportCsv=async()=>{const r=await request("/api/export/tracks.csv"),b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="tracks.csv";a.click();URL.revokeObjectURL(u)};
 const importCsv=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await request("/api/import/tracks.csv",{method:"POST",headers:{"Content-Type":"text/csv"},body:await f.text()}),d=await r.json();setMessage(`IMPORTED · ${d.imported||0}`);await refresh()}catch(e){setMessage(e.message)}e.target.value=""};
 const deleteData=async()=>{if(!confirm("DELETE ALL DATA? This cannot be undone."))return;try{await json("/api/data/delete",{method:"POST",body:JSON.stringify({confirm:"DELETE"})});setCurrent(null);setQueue([]);setMessage("DATA DELETED");await refresh()}catch(e){setMessage(e.message)}};
 return <main className="ipod-page"><section className="ipod"><div className="screen"><header className="screen-top"><button className="screen-title" onClick={home}>daksh music</button><span className="status-dot">●</span></header><div className="screen-body">{message&&<div className="banner">{message}</div>}{windowName==="home"?<Home items={MENU} index={menuIndex} onSelect={selectMenu}/>:<WindowHeader title={windowName} onBack={home}/>} {windowName!=="home"&&<Window name={windowName} current={current} mode={mode} audio={audio} playlist={playlist} albums={albums} history={history} queue={queue} query={query} setQuery={setQuery} results={results} search={search} play={playTrack} add={add} remove={remove} next={next} playAlbum={playAlbum} settingsTab={settingsTab} setSettingsTab={setSettingsTab} exportCsv={exportCsv} upload={()=>upload.current?.click()} deleteData={deleteData} busy={busy}/>}<input ref={upload} hidden type="file" accept=".csv,text/csv" onChange={importCsv}/></div></div><div className="wheel-area"><div className="wheel" onPointerDown={handleWheelPointerDown} onPointerUp={handleWheelPointerUp} onPointerCancel={()=>{wheelStart.current=null}}><button type="button" className="wheel-menu" onClick={e=>{e.stopPropagation();home()}}>MENU</button><button type="button" className="wheel-prev" onClick={e=>{e.stopPropagation();windowName==="home"?moveMenu(-1):home()}}>‹</button><button type="button" className="wheel-next" onClick={e=>{e.stopPropagation();windowName==="home"?moveMenu(1):next()}}>›</button><button type="button" className="wheel-play" onClick={e=>{e.stopPropagation();audio.current?.paused?audio.current?.play():audio.current?.pause()}}>▶❙❙</button><button type="button" className="wheel-center" aria-label="Select" onClick={e=>{e.stopPropagation();windowName==="home"?selectMenu():open("Now Playing")}}/></div><div className="click-hint">{windowName==="home"?"CLICK / TAP CENTER TO SELECT":"MENU = HOME · SWIPE"}</div></div><footer className="footer">daksh music · {mode} mode</footer></section></main>;
}
function Home({items,index,onSelect}){return <nav className="menu-list">{items.map((x,i)=><button type="button" key={x} className={`menu-row ${i===index?"selected":""}`} onClick={()=>onSelect(i)} onTouchEnd={()=>onSelect(i)}><span>{x}</span><span className="arrow">›</span></button>)}</nav>}
function WindowHeader({title,onBack}){return <div className="window-header"><button type="button" onClick={onBack}>‹</button><strong>{title}</strong><span/></div>}
function Window({name,...p}){if(name==="Now Playing")return <NowPlaying {...p}/>;if(name==="Playlist")return <Playlist {...p}/>;if(name==="Search")return <Search {...p}/>;if(name==="Album")return <Albums {...p}/>;if(name==="Queue")return <Queue {...p}/>;return <Settings {...p}/>}
function NowPlaying({current,mode,audio,next}){let meta=current?.metadata_json;if(typeof meta==="string")try{meta=JSON.parse(meta)}catch{}const preview=meta?.deezer?.preview;return <div className="now-playing"><div className="art">{current?.artwork_url?<img src={current.artwork_url} alt=""/>:"♪"}</div><div className="np-info"><small>{mode.toUpperCase()} MODE</small><strong>{current?.title||"Nothing playing"}</strong><small>{current?.artist||"—"}</small><small>{current?.album_name||"—"}</small><div className="toolbar"><button type="button" className="tiny-btn" onClick={()=>audio.current?.paused?audio.current?.play():audio.current?.pause()}>Play/Pause</button><button type="button" className="tiny-btn" onClick={next}>Next</button></div>{preview?<audio ref={audio} src={preview} controls onEnded={next}/>:<small>No preview available</small>}</div></div>}
function Playlist({playlist,play,remove}){return <div>{playlist.length?playlist.map(r=><div className="track-line" key={r.playlist_entry_id}><div className="track-copy" onClick={()=>play(r)}><strong>{r.title}</strong><small>{r.artist} · {r.album_name||"Unknown album"}</small></div><button type="button" className="tiny-btn" onClick={()=>play(r)}>▶</button><button type="button" className="tiny-btn" onClick={()=>remove(r.playlist_entry_id)}>×</button></div>):<div className="empty">Playlist is empty.</div>}</div>}
function Search({query,setQuery,search,results,play,add,busy}){return <div><form className="toolbar" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Song, artist, album…"/><button type="submit" className="tiny-btn">Search</button></form>{busy&&<div className="empty">Searching…</div>}{results.map(x=><div className="track-line" key={x.id}><div className="thumb">{x.album?.cover_medium?<img src={x.album.cover_medium} alt=""/>:"♪"}</div><div className="track-copy"><strong>{x.title}</strong><small>{x.artist?.name} · {x.album?.title}</small></div><button type="button" className="tiny-btn" onClick={()=>play(deezerTrack(x))}>▶</button><button type="button" className="tiny-btn" onClick={()=>add(x)}>+</button></div>)}</div>}
function Albums({albums,history,playAlbum}){return <div>{history.length>0&&<><div className="subhead">RECENT ALBUMS</div>{history.map(a=><AlbumRow key={`h-${a.album_id}`} album={a} playAlbum={playAlbum}/>)}</>}{albums.length?albums.map(a=><AlbumRow key={a.id} album={a} playAlbum={playAlbum}/>):<div className="empty">No albums.</div>}</div>}
function AlbumRow({album,playAlbum}){return <div className="track-line"><div className="thumb">{album.artwork_url?<img src={album.artwork_url} alt=""/>:"♪"}</div><div className="track-copy"><strong>{album.title}</strong><small>{album.artist||"Unknown artist"}{album.track_count!=null?` · ${album.track_count} tracks`:""}</small></div><button type="button" className="tiny-btn" onClick={()=>playAlbum(album)}>Play</button></div>}
function Queue({queue,current,play,next,mode}){return <div>{queue.length?queue.map((r,i)=><div className={`track-line ${current?.id===r.id?"selected":""}`} key={r.queue_entry_id||r.id||i}><div className="track-copy"><strong>{r.title}</strong><small>{r.artist} · {r.album_name||""}</small></div><button type="button" className="tiny-btn" onClick={()=>play(r)}>▶</button></div>):<div className="empty">{mode} queue is empty.</div>}<div className="toolbar"><button type="button" className="tiny-btn" onClick={next}>Next</button></div></div>}
function Settings({settingsTab,setSettingsTab,mode,exportCsv,upload,deleteData}){const items=[["params","Params"],["csv","Download tracklist CSV"],["upload","Upload data from CSV"],["delete","Delete data"]];return <div><div className="menu-list settings-list">{items.map(([k,v])=><button type="button" key={k} className={`menu-row ${settingsTab===k?"selected":""}`} onClick={()=>setSettingsTab(k)} onTouchEnd={()=>setSettingsTab(k)}><span>{v}</span><span className="arrow">›</span></button>)}</div>{settingsTab==="params"&&<div className="settings-card">Playback: <strong>{mode}</strong><br/>API: <code>{API||"same-origin"}</code></div>}{settingsTab==="csv"&&<div className="settings-card"><button type="button" className="tiny-btn" onClick={exportCsv}>Download CSV</button></div>}{settingsTab==="upload"&&<div className="settings-card"><button type="button" className="tiny-btn" onClick={upload}>Choose CSV</button></div>}{settingsTab==="delete"&&<div className="settings-card danger"><button type="button" className="tiny-btn" onClick={deleteData}>DELETE ALL DATA</button></div>}</div>}
createRoot(document.getElementById("root")).render(<App/>);
