import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = import.meta.env.VITE_QUEUE_API_URL?.replace(/\/$/, "") || "";
const request = async (path, options = {}) => {
  const r = await fetch(`${API}${path}`, {
    ...options,
    headers: { ...(options.body ? { "Content-Type": options.headers?.["Content-Type"] || "application/json" } : {}), ...(options.headers || {}) },
  });
  if (!r.ok) { const d = await r.json().catch(() => ({})); throw Error(d.error || `API error ${r.status}`); }
  return r;
};
const json = async (path, options = {}) => (await request(path, options)).json();
const deezerTrack = x => ({ title:x.title, artist:x.artist?.name||"Unknown artist", album_id:x.album?.id??null, album_name:x.album?.title??null, source:"deezer", source_id:String(x.id), source_url:`https://www.deezer.com/track/${x.id}`, artwork_url:x.album?.cover_xl||x.album?.cover_medium||null, duration_ms:Number(x.duration||0)*1000, metadata_json:{deezer:x,deezer_album_id:x.album?.id??null} });
const meta = t => { let m=t?.metadata_json; if(typeof m==="string") try{m=JSON.parse(m)}catch{m=null} return m; };
const preview = t => meta(t)?.deezer?.preview || null;
const fmt = s => { s=Number(s)||0; return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`; };
const MENU=[
 {key:"Now Playing",label:"Now Playing",icon:"disc"},{key:"Playlist",label:"Playlist",icon:"list"},{key:"Search",label:"Search",icon:"search"},{key:"Album",label:"Albums",icon:"grid"},{key:"Queue",label:"Queue",icon:"queue"},{key:"Settings",label:"Settings",icon:"settings"}
];
function Icon({name,size=20,...p}){const s={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round",strokeLinejoin:"round",...p};switch(name){case"disc":return <svg {...s}><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2.4" fill="currentColor" stroke="none"/></svg>;case"list":return <svg {...s}><path d="M8 6h12M8 12h12M8 18h12"/><path d="M4 6h.1M4 12h.1M4 18h.1"/></svg>;case"search":return <svg {...s}><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></svg>;case"grid":return <svg {...s}><rect x="4" y="4" width="7" height="7" rx="1"/><rect x="13" y="4" width="7" height="7" rx="1"/><rect x="4" y="13" width="7" height="7" rx="1"/><rect x="13" y="13" width="7" height="7" rx="1"/></svg>;case"queue":return <svg {...s}><path d="M4 6h11M4 12h11M4 18h7"/><path d="m17 15 4 3-4 3z" fill="currentColor" stroke="none"/></svg>;case"settings":return <svg {...s}><circle cx="12" cy="12" r="3"/><path d="M19.4 13a7.9 7.9 0 0 0 0-2l2-1.5-2-3.4-2.4.6a8 8 0 0 0-1.7-1l-.4-2.5h-4l-.4 2.5a8 8 0 0 0-1.7 1l-2.4-.6-2 3.4L6.6 11a7.9 7.9 0 0 0 0 2l-2 1.5 2 3.4 2.4-.6a8 8 0 0 0 1.7 1l.4 2.5h4l.4-2.5a8 8 0 0 0 1.7-1l2.4.6 2-3.4z"/></svg>;case"play":return <svg {...s}><path d="m7 5 12 7-12 7z" fill="currentColor" stroke="none"/></svg>;case"pause":return <svg {...s}><rect x="6" y="5" width="4" height="14" rx="1" fill="currentColor" stroke="none"/><rect x="14" y="5" width="4" height="14" rx="1" fill="currentColor" stroke="none"/></svg>;case"next":return <svg {...s}><path d="m6 5 10 7-10 7z" fill="currentColor" stroke="none"/><rect x="17" y="5" width="2.4" height="14" rx="1" fill="currentColor" stroke="none"/></svg>;case"prev":return <svg {...s}><path d="m18 5-10 7 10 7z" fill="currentColor" stroke="none"/><rect x="4.6" y="5" width="2.4" height="14" rx="1" fill="currentColor" stroke="none"/></svg>;case"plus":return <svg {...s}><path d="M12 5v14M5 12h14"/></svg>;case"x":return <svg {...s}><path d="m6 6 12 12M18 6 6 18"/></svg>;case"chevron-left":return <svg {...s}><path d="m15 6-6 6 6 6"/></svg>;case"chevron-right":return <svg {...s}><path d="m9 6 6 6-6 6"/></svg>;case"upload":return <svg {...s}><path d="M12 16V4M6 10l6-6 6 6M4 20h16"/></svg>;case"download":return <svg {...s}><path d="M12 4v12M6 12l6 6 6-6M4 20h16"/></svg>;case"trash":return <svg {...s}><path d="M5 7h14M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2M7 7l1 13h8l1-13"/></svg>;case"note":return <svg {...s}><path d="M9 18V5l10-2v13"/><circle cx="7" cy="18" r="2.4" fill="currentColor" stroke="none"/><circle cx="17" cy="16" r="2.4" fill="currentColor" stroke="none"/></svg>;default:return null;}}

function App(){
 const [page,setPage]=useState("home"),[menu,setMenu]=useState(0),[mode,setMode]=useState("track"),[current,setCurrent]=useState(null),[playlist,setPlaylist]=useState([]),[albums,setAlbums]=useState([]),[history,setHistory]=useState([]),[queue,setQueue]=useState([]),[results,setResults]=useState([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[settings,setSettings]=useState("params"),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[duration,setDuration]=useState(0),[clock,setClock]=useState(new Date());
 const audio=useRef(null),upload=useRef(null),wheel=useRef(null);
 const open=n=>{setPage(n);setMenu(Math.max(0,MENU.findIndex(x=>x.key===n)));};
 const refresh=async()=>{try{const [p,a,h]=await Promise.all([json("/api/playlist"),json("/api/library/albums?limit=1000"),json("/api/albums/history")]);setPlaylist(p.tracks||[]);setAlbums(a.albums||[]);setHistory(h.albums||[]);}catch(e){setMessage(e.message)}};
 const refreshState=async()=>{try{const key=mode==="album"?"album-current":"default";const q=await json(`/api/queue?queue_key=${key}`);setQueue(q.tracks||[]);}catch(e){setMessage(e.message)}};
 useEffect(()=>{refresh();refreshState();const t=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(t)},[mode]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(""),2800);return()=>clearTimeout(t)},[message]);
 useEffect(()=>{const a=audio.current;if(!a)return;const tm=()=>setPos(a.currentTime||0),md=()=>setDuration(a.duration||0),pl=()=>setPlaying(true),pa=()=>setPlaying(false),end=()=>next();a.addEventListener("timeupdate",tm);a.addEventListener("loadedmetadata",md);a.addEventListener("play",pl);a.addEventListener("pause",pa);a.addEventListener("ended",end);return()=>{a.removeEventListener("timeupdate",tm);a.removeEventListener("loadedmetadata",md);a.removeEventListener("play",pl);a.removeEventListener("pause",pa);a.removeEventListener("ended",end)}},[current,queue,playlist]);
 const switchMode=async target=>{if(target===mode)return true;if(!confirm(`Move device to ${target} mode?\nThe current playback session will be replaced.`))return false;try{await json("/api/playback/mode",{method:"POST",body:JSON.stringify({mode:target})});setMode(target);setQueue([]);setCurrent(null);return true}catch(e){setMessage(e.message);return false}};
 const playTrack=async(track)=>{if(!(await switchMode("track")))return;try{setBusy(true);let id=track.id;if(!id){const r=await json("/api/tracks/resolve",{method:"POST",body:JSON.stringify(track)});id=r.track_id}const r=await json("/api/play/track",{method:"POST",body:JSON.stringify({track_id:id})});setCurrent(r.track||{...track,id});open("Now Playing");setMessage("Preparing track…");setTimeout(()=>audio.current?.play().catch(()=>{}),100);await refresh();await refreshState()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const playAlbum=async album=>{if(!(await switchMode("album")))return;try{setBusy(true);const r=await json(`/api/play/album/${album.id}`,{method:"POST"});setCurrent(r.tracks?.[0]||r.track||null);open("Now Playing");setMessage(`Loading album · ${album.title}`);await refresh();await refreshState();setTimeout(()=>audio.current?.play().catch(()=>{}),100)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const next=async()=>{if(!queue.length)return;const i=queue.findIndex(x=>x.id===current?.id);await playTrack(queue[(i<0?0:i+1)%queue.length])};
 const prev=async()=>{if(!queue.length)return;const i=queue.findIndex(x=>x.id===current?.id);await playTrack(queue[(i<=0?queue.length-1:i-1)])};
 const shufflePlaylist=async()=>{if(!playlist.length)return;if(!(await switchMode("track")))return;try{await json("/api/playback/mode",{method:"POST",body:JSON.stringify({mode:"track"})});const shuffled=[...playlist].sort(()=>Math.random()-.5);await Promise.all(shuffled.map(t=>json("/api/queue/add",{method:"POST",body:JSON.stringify({queue_key:"default",track:{title:t.title,artist:t.artist,album_id:t.album_id,album_name:t.album_name,source:t.source,source_id:t.source_id,source_url:t.source_url,artwork_url:t.artwork_url,duration_ms:t.duration_ms,metadata_json:t.metadata_json}})})));await refreshState();await playTrack(shuffled[0])}catch(e){setMessage(e.message)}};
 const search=async e=>{e.preventDefault();if(!query.trim())return;try{setBusy(true);const d=await json(`/api/search?q=${encodeURIComponent(query)}&limit=25`);setResults(d.data||[])}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const add=async x=>{try{const t=deezerTrack(x),r=await json("/api/tracks/resolve",{method:"POST",body:JSON.stringify(t)});await json("/api/playlist",{method:"POST",body:JSON.stringify({track_id:r.track_id})});await refresh();setMessage(`Added ${t.title}`)}catch(e){setMessage(e.message)}};
 const remove=async id=>{try{await request(`/api/playlist/${id}`,{method:"DELETE"});await refresh()}catch(e){setMessage(e.message)}};
 const toggle=()=>{if(!audio.current)return;audio.current.paused?audio.current.play().catch(()=>{}):audio.current.pause()};
 const seek=e=>{if(!audio.current||!duration)return;const r=e.currentTarget.getBoundingClientRect();audio.current.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*duration};
 const exportCsv=async()=>{const r=await request("/api/export/tracks.csv"),b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="tracks.csv";a.click();URL.revokeObjectURL(u)};
 const importCsv=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await request("/api/import/tracks.csv",{method:"POST",headers:{"Content-Type":"text/csv"},body:await f.text()}),d=await r.json();setMessage(`Imported ${d.imported||0}`);refresh()}catch(e){setMessage(e.message)}e.target.value=""};
 const deleteData=async()=>{if(!confirm("Delete all data? This cannot be undone."))return;try{await json("/api/data/delete",{method:"POST",body:JSON.stringify({confirm:"DELETE"})});setCurrent(null);setQueue([]);await refresh()}catch(e){setMessage(e.message)}};
 const status=current?.storage_status||"unknown";const progress=status==="ready"||status==="completed"?100:status==="running"||status==="downloading"?60:status==="queued"?25:status==="failed"?100:0;
 return <main className="ipod-page"><section className="ipod"><div className="screen"><audio ref={audio} src={preview(current)||undefined} preload="none"/><header className="status-bar"><button className="brand" onClick={()=>open("home")}>daksh music</button><span className="status-right"><span className="time">{clock.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span><span className={`live-dot ${playing?"on":""}`}/></span></header>{message&&<div className="toast">{message}</div>}{page!=="home"&&<div className="window-header"><button onClick={()=>open("home")}><Icon name="chevron-left" size={20}/></button><strong>{MENU.find(x=>x.key===page)?.label}</strong><span/></div>}<div className="screen-body">
 {page==="home"&&<Home index={menu} items={MENU} onSelect={i=>open(MENU[i].key)}/>} 
 {page==="Now Playing"&&<NowPlaying current={current} mode={mode} status={status} progress={progress} playing={playing} pos={pos} duration={duration} toggle={toggle} next={next} prev={prev} seek={seek}/>} 
 {page==="Playlist"&&<Playlist rows={playlist} current={current} play={playTrack} remove={remove} shuffle={shufflePlaylist}/>} 
 {page==="Search"&&<Search query={query} setQuery={setQuery} submit={search} results={results} play={x=>playTrack(deezerTrack(x))} add={add} busy={busy}/>} 
 {page==="Album"&&<Albums albums={albums} history={history} play={playAlbum}/>} 
 {page==="Queue"&&<Queue rows={queue} current={current} play={playTrack} mode={mode}/>} 
 {page==="Settings"&&<Settings tab={settings} setTab={setSettings} mode={mode} exportCsv={exportCsv} upload={()=>upload.current?.click()} deleteData={deleteData}/>}<input ref={upload} hidden type="file" accept=".csv,text/csv" onChange={importCsv}/></div></div>
 <div className="wheel-area"><div className="wheel" onPointerDown={e=>{wheel.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId)}} onPointerUp={e=>{const s=wheel.current;if(!s)return;wheel.current=null;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.abs(dy)>20&&Math.abs(dy)>Math.abs(dx)){setMenu(i=>(i+(dy>0?-1:1)+MENU.length)%MENU.length);return}if(Math.abs(dx)>20&&page!=="home"){dx>0?open("home"):open("Now Playing");return}if(page==="home"&&Math.abs(dx)<20&&Math.abs(dy)<20)open(MENU[menu].key)}}><button className="wheel-btn wheel-menu" onClick={()=>open("home")}>MENU</button><button className="wheel-btn wheel-prev" onClick={prev}><Icon name="prev" size={16}/></button><button className="wheel-btn wheel-next" onClick={next}><Icon name="next" size={16}/></button><button className="wheel-btn wheel-play" onClick={toggle}><Icon name={playing?"pause":"play"} size={16}/></button><button className="wheel-center" onClick={()=>page==="home"?open(MENU[menu].key):toggle()}/></div></div><footer className="footer">daksh music · {mode} mode</footer></section></main>;
}
function Home({items,index,onSelect}){return <nav className="menu-list">{items.map((x,i)=><button key={x.key} className={`menu-row ${i===index?"selected":""}`} onClick={()=>onSelect(i)}><span className="menu-row-icon"><Icon name={x.icon} size={16}/></span><span className="menu-row-label">{x.label}</span><Icon name="chevron-right" size={16}/></button>)}</nav>}
function NowPlaying({current,mode,status,progress,playing,pos,duration,toggle,next,prev,seek}){return <div className="now-playing"><div className="np-bg" style={current?.artwork_url?{backgroundImage:`url(${current.artwork_url})`}:undefined}/><div className="np-content"><div className="np-art">{current?.artwork_url?<img src={current.artwork_url} alt=""/>:<Icon name="note" size={36}/>}</div><div className="np-meta"><strong>{current?.title||"Nothing playing"}</strong><small>{current?.artist||"Select a song"}</small>{current?.album_name&&<small className="np-album">{current.album_name}</small>}</div>{current&&<div className="acquisition"><div className="acquisition-label"><span>Acquisition</span><strong>{status}</strong></div><div className="np-progress"><div className="np-progress-fill" style={{width:`${progress}%`}}/></div></div>}<div className="np-progress" onClick={seek}><div className="np-progress-fill" style={{width:`${duration?pos/duration*100:0}%`}}/></div><div className="np-times"><span>{fmt(pos)}</span><span>{fmt(duration)}</span></div><div className="np-controls"><button className="round-btn lg" onClick={prev}><Icon name="prev" size={16}/></button><button className="round-btn xl accent" onClick={toggle}><Icon name={playing?"pause":"play"} size={22}/></button><button className="round-btn lg" onClick={next}><Icon name="next" size={16}/></button></div><small className="np-mode">{mode} mode · queue updates automatically</small></div></div>}
function Playlist({rows,current,play,remove,shuffle}){return <div className="list"><button className="pill-btn" onClick={shuffle}>Shuffle playlist</button>{rows.length?rows.map(r=><div className={`row ${current?.id===r.id?"active":""}`} key={r.playlist_entry_id}><button className="row-tap" onClick={()=>play(r)}><span className="row-thumb">{r.artwork_url?<img src={r.artwork_url} alt=""/>:<Icon name="note" size={16}/>}</span><span className="row-copy"><strong>{r.title}</strong><small>{r.artist} · {r.album_name||"Unknown album"}</small></span></button><button className="icon-btn" onClick={()=>remove(r.playlist_entry_id)}><Icon name="x" size={16}/></button></div>):<Empty text="Your playlist is empty"/>}</div>}
function Search({query,setQuery,submit,results,play,add,busy}){return <div className="search-pane"><form className="search-bar" onSubmit={submit}><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Songs, artists, albums"/></form>{busy&&<Empty text="Searching…"/>}<div className="list">{results.map(x=><div className="row" key={x.id}><button className="row-tap" onClick={()=>play(x)}><span className="row-thumb">{x.album?.cover_medium?<img src={x.album.cover_medium} alt=""/>:<Icon name="note" size={16}/>}</span><span className="row-copy"><strong>{x.title}</strong><small>{x.artist?.name} · {x.album?.title}</small></span></button><button className="icon-btn" onClick={()=>add(x)}><Icon name="plus" size={16}/></button></div>)}</div></div>}
function Albums({albums,history,play}){return <div className="list">{history.length>0&&<div className="section-label">Recently played</div>}{history.map(a=><AlbumRow key={`h-${a.album_id}`} album={a} play={play}/>)}{albums.length>0&&<div className="section-label">Your library</div>}{albums.length?albums.map(a=><AlbumRow key={a.id} album={a} play={play}/>):(!history.length&&<Empty text="No albums yet"/>)}</div>}
function AlbumRow({album,play}){return <div className="row"><button className="row-tap" onClick={()=>play(album)}><span className="row-thumb sq">{album.artwork_url?<img src={album.artwork_url} alt=""/>:<Icon name="note" size={16}/>}</span><span className="row-copy"><strong>{album.title}</strong><small>{album.artist||"Unknown artist"}{album.track_count!=null?` · ${album.track_count} tracks`:""}</small></span></button></div>}
function Queue({rows,current,play,mode}){return <div className="list">{rows.length?rows.map((r,i)=><div className={`row ${current?.id===r.id?"active":""}`} key={r.queue_entry_id||r.id||i}><button className="row-tap" onClick={()=>play(r)}><span className="row-index">{i+1}</span><span className="row-copy"><strong>{r.title}</strong><small>{r.artist} · {r.album_name||""}{r.storage_status?` · ${r.storage_status}`:""}</small></span></button></div>):<Empty text={`${mode} queue is empty`}/>}</div>}
function Settings({tab,setTab,mode,exportCsv,upload,deleteData}){const items=[["params","Playback"],["csv","Export library"],["upload","Import library"],["delete","Delete all data"]];return <div className="settings"><div className="grouped-list">{items.map(([k,v])=><button key={k} className={`grouped-row ${tab===k?"active":""} ${k==="delete"?"danger":""}`} onClick={()=>setTab(k)}><span>{v}</span><Icon name="chevron-right" size={14}/></button>)}</div>{tab==="params"&&<div className="card"><div className="kv"><span>Playback mode</span><strong>{mode}</strong></div><div className="kv"><span>Queue</span><strong>Automatic</strong></div><div className="kv"><span>API</span><code>{API||"same-origin"}</code></div></div>}{tab==="csv"&&<div className="card"><p>Download the track library as CSV.</p><button className="pill-btn" onClick={exportCsv}><Icon name="download" size={14}/> Download CSV</button></div>}{tab==="upload"&&<div className="card"><p>Import tracks from CSV.</p><button className="pill-btn" onClick={upload}><Icon name="upload" size={14}/> Choose CSV</button></div>}{tab==="delete"&&<div className="card danger"><p>This permanently deletes library data.</p><button className="pill-btn danger" onClick={deleteData}><Icon name="trash" size={14}/> Delete all data</button></div>}</div>}
function Empty({text}){return <div className="empty">{text}</div>}
createRoot(document.getElementById("root")).render(<App/>);
