import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const API=import.meta.env.VITE_QUEUE_API_URL?.replace(/\/$/,"")||"";
const get=async(p,o={})=>{const r=await fetch(`${API}${p}`,{...o,headers:{...(o.body?{"Content-Type":o.headers?.["Content-Type"]||"application/json"}:{}),...(o.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`API error ${r.status}`)}return r};
const json=async(p,o={})=>(await get(p,o)).json();
const trackFromDeezer=x=>({title:x.title,artist:x.artist?.name||"Unknown artist",album_id:x.album?.id??null,album_name:x.album?.title??null,source:"deezer",source_id:String(x.id),source_url:`https://www.deezer.com/track/${x.id}`,artwork_url:x.album?.cover_xl||x.album?.cover_medium||null,duration_ms:Number(x.duration||0)*1000,metadata_json:{deezer:x}});
function App(){
 const [tab,setTab]=useState("Now Playing"),[sub,setSub]=useState("params"),[tracks,setTracks]=useState([]),[albums,setAlbums]=useState([]),[playlist,setPlaylist]=useState([]),[history,setHistory]=useState([]),[current,setCurrent]=useState(null),[mode,setMode]=useState("track"),[albumTracks,setAlbumTracks]=useState([]),[albumIndex,setAlbumIndex]=useState(0),[results,setResults]=useState([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),audio=useRef(null),file=useRef(null);
 const tabs=useMemo(()=>["Now Playing","Playlist","Search","Album","Queue","Settings"],[]);
 const refresh=async()=>{try{const[t,a,p,h]=await Promise.all([json("/api/library/tracks?limit=2000"),json("/api/library/albums?limit=1000"),json("/api/playlist"),json("/api/albums/history")]);setTracks(t.tracks||[]);setAlbums(a.albums||[]);setPlaylist(p.tracks||[]);setHistory(h.albums||[])}catch(e){setMessage(e.message)}};
 useEffect(()=>{refresh()},[]);
 const changeMode=async(next)=>{if(next===mode)return true;if(!confirm(`Move device to ${next} mode?\nThe current playback session will be replaced.`))return false;try{await json("/api/playback/mode",{method:"POST",body:JSON.stringify({mode:next})});setMode(next);setAlbumTracks([]);setAlbumIndex(0);setMessage(`Device moved to ${next} mode`);return true}catch(e){setMessage(e.message);return false}};
 const resolve=async(t)=>{const r=await json("/api/tracks/resolve",{method:"POST",body:JSON.stringify(t)});return {...t,id:r.track_id}};
 const playTrack=async(t)=>{if(mode!=="track"&&!(await changeMode("track")))return;try{const x=t.id? t:await resolve(t);await json("/api/play/track",{method:"POST",body:JSON.stringify({track_id:x.id})});setCurrent(x);setAlbumTracks([]);setTab("Now Playing");setTimeout(()=>audio.current?.play().catch(()=>{}),50);refresh()}catch(e){setMessage(e.message)}};
 const playAlbum=async(a)=>{if(mode!=="album"&&!(await changeMode("album")))return;try{const d=await json(`/api/library/albums/${a.id}`);await json("/api/play/album",{method:"POST",body:JSON.stringify({album_id:a.id})});setAlbumTracks(d.tracks||[]);setAlbumIndex(0);setCurrent(d.tracks?.[0]||null);setTab("Now Playing");setMessage(`Album mode · ${a.title}`);setTimeout(()=>audio.current?.play().catch(()=>{}),50);refresh()}catch(e){setMessage(e.message)}};
 const next=async()=>{if(mode==="album"&&albumTracks.length){const n=(albumIndex+1)%albumTracks.length;setAlbumIndex(n);setCurrent(albumTracks[n]);setTimeout(()=>audio.current?.play().catch(()=>{}),50);return}if(!playlist.length)return;const i=Math.max(0,playlist.findIndex(x=>x.id===current?.id));playTrack(playlist[(i+1)%playlist.length])};
 const search=async e=>{e.preventDefault();if(!query.trim())return;try{const d=await json(`/api/search?q=${encodeURIComponent(query)}&limit=25`);setResults(d.data||[])}catch(e){setMessage(e.message)}};
 const add=async x=>{try{const t=await resolve(trackFromDeezer(x));await json("/api/playlist",{method:"POST",body:JSON.stringify({track_id:t.id})});setMessage(`Added ${t.title}`);refresh()}catch(e){setMessage(e.message)}};
 const remove=async id=>{try{await get(`/api/playlist/${id}`,{method:"DELETE"});refresh()}catch(e){setMessage(e.message)}};
 const exportCsv=async()=>{const r=await get("/api/export/tracks.csv"),b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="tracks.csv";a.click();URL.revokeObjectURL(u)};
 const importCsv=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=await json("/api/import/tracks.csv",{method:"POST",headers:{"Content-Type":"text/csv"},body:await f.text()});setMessage(`Imported ${d.imported} tracks`);refresh()}catch(e){setMessage(e.message)}e.target.value=""};
 const wipe=async()=>{if(!confirm("Delete all tracks, playlists, queues, jobs and cache records?"))return;try{await json("/api/data/delete",{method:"POST",body:JSON.stringify({confirm:"DELETE"})});setCurrent(null);setAlbumTracks([]);setMessage("All data deleted");refresh()}catch(e){setMessage(e.message)}};
 return <main className="ipod-page"><section className="ipod"><div className="screen"><div className="screen-top"><span>daksh music</span><span className="battery"><i/></span></div><div className="screen-body">{message&&<div className="banner">{message}</div>}<nav className="menu-list">{tabs.map(t=><button className={`menu-row ${tab===t?"selected":""}`} key={t} onClick={()=>setTab(t)}><span>{t}</span><span className="arrow">›</span></button>)}</nav>
 {tab==="Now Playing"&&<Now current={current} mode={mode} audio={audio} next={next} end={next}/>} 
 {tab==="Playlist"&&<Playlist rows={playlist} play={playTrack} remove={remove}/>} 
 {tab==="Search"&&<Search query={query} setQuery={setQuery} submit={search} results={results} play={playTrack} add={add}/>} 
 {tab==="Album"&&<Albums albums={albums} history={history} play={playAlbum}/>} 
 {tab==="Queue"&&<Queue rows={mode==="album"?albumTracks:playlist} current={current} mode={mode} play={playTrack} next={next}/>} 
 {tab==="Settings"&&<Settings sub={sub} setSub={setSub} mode={mode} exportCsv={exportCsv} importCsv={()=>file.current?.click()} wipe={wipe}/>}<input ref={file} hidden type="file" accept=".csv,text/csv" onChange={importCsv}/></div></div><div className="wheel-area"><div className="wheel"><button className="menu" onClick={()=>setTab("Now Playing")}>MENU</button><button className="prev" onClick={()=>setTab("Playlist")}>‹</button><button className="next" onClick={next}>›</button><button className="play" onClick={()=>audio.current?.paused?audio.current?.play():audio.current?.pause()}>▶❙❙</button><button className="center" onClick={()=>setTab("Now Playing")}/></div><div className="click-hint">{mode.toUpperCase()} MODE · SELECT</div></div><div className="footer">daksh music · {mode} mode</div></section></main>}
function Now({current,mode,audio,next,end}){const preview=current?.metadata_json?.deezer?.preview;return <div className="now-playing"><div className="art">{current?.artwork_url?<img src={current.artwork_url} alt=""/>:"♪"}</div><div className="np-info"><small>{mode.toUpperCase()} MODE</small><strong>{current?.title||"Nothing playing"}</strong><small>{current?.artist||"—"}</small><small>{current?.album_name||"—"}</small><div className="toolbar"><button className="tiny-btn" onClick={()=>audio.current?.paused?audio.current?.play():audio.current?.pause()}>Play/Pause</button><button className="tiny-btn" onClick={next}>Next</button></div>{preview?<audio ref={audio} src={preview} controls onEnded={end}/>:<small>No Deezer preview available</small>}</div></div>}
function Playlist({rows,play,remove}){return <><div className="toolbar"><strong>Playlist · {rows.length} tracks</strong></div>{rows.length?rows.map(r=><div className="track-line" key={r.playlist_entry_id}><div className="track-copy" onClick={()=>play(r)}><strong>{r.title}</strong><small>{r.artist} · {r.album_name||"Unknown album"}</small></div><button className="tiny-btn" onClick={()=>play(r)}>▶</button><button className="tiny-btn" onClick={()=>remove(r.playlist_entry_id)}>×</button></div>):<div className="empty">Playlist is empty.</div>}</>}
function Search({query,setQuery,submit,results,play,add}){return <><form className="toolbar" onSubmit={submit}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Song, artist, album…"/><button className="tiny-btn">Search</button></form>{results.map(x=>{const t=trackFromDeezer(x);return <div className="track-line" key={x.id}><div className="thumb">{x.album?.cover_medium?<img src={x.album.cover_medium} alt=""/>:"♪"}</div><div className="track-copy"><strong>{x.title}</strong><small>{x.artist?.name} · {x.album?.title}</small></div><button className="tiny-btn" onClick={()=>play(t)}>▶</button><button className="tiny-btn" onClick={()=>add(x)}>+</button></div>})}</>}
function Albums({albums,history,play}){return <><div className="toolbar"><strong>Album cache</strong></div>{history.length>0&&<><div className="empty">Last 5 played albums</div>{history.map(a=><div className="track-line" key={`h${a.album_id}`}><div className="thumb">{a.artwork_url?<img src={a.artwork_url} alt=""/>:"♪"}</div><div className="track-copy"><strong>{a.title}</strong><small>{a.artist}</small></div><button className="tiny-btn" onClick={()=>play(a)}>Play album</button></div>)}</>}{albums.map(a=><div className="track-line" key={a.id}><div className="thumb">{a.artwork_url?<img src={a.artwork_url} alt=""/>:"♪"}</div><div className="track-copy"><strong>{a.title}</strong><small>{a.artist} · {a.track_count} tracks</small></div><button className="tiny-btn" onClick={()=>play(a)}>Play album</button></div>)}</>}
function Queue({rows,current,mode,play,next}){return <><div className="toolbar"><strong>{mode} queue · {rows.length}</strong><button className="tiny-btn" onClick={next}>Next</button></div>{rows.map((r,i)=><div className={`track-line ${current?.id===r.id?"selected":""}`} key={r.id||i}><div className="track-copy"><strong>{r.title}</strong><small>{r.artist} · {r.album_name||""}</small></div><button className="tiny-btn" onClick={()=>play(r)}>▶</button></div>)}</>}
function Settings({sub,setSub,mode,exportCsv,importCsv,wipe}){const items=[["params","Params"],["csv","Download tracklist as a CSV"],["delete","Delete data"],["upload","Upload data from CSV"]];return <><div className="menu-list">{items.map(([k,v])=><button className={`menu-row ${sub===k?"selected":""}`} key={k} onClick={()=>setSub(k)}><span>{v}</span><span className="arrow">›</span></button>)}</div>{sub==="params"&&<div className="empty">Playback mode: <strong>{mode}</strong><br/>API: <code>{API||"same-origin"}</code></div>}{sub==="csv"&&<div className="toolbar"><button className="tiny-btn" onClick={exportCsv}>Download CSV</button></div>}{sub==="upload"&&<div className="toolbar"><button className="tiny-btn" onClick={importCsv}>Choose CSV</button></div>}{sub==="delete"&&<div className="empty"><button className="tiny-btn" onClick={wipe}>DELETE ALL DATA</button></div>}</>}
createRoot(document.getElementById("root")).render(<App/>);
